### ISSUE TITLE
How to use chess engine instead of the provided algorithm?

### ISSUE THREAD

**Issue by ArjanAswal** [PScottZero/EnPassant#3]
First of all really cool stuff!

Can you tell me how can I integrate this with my custom Stockfish chess engine (which works in UCI protocol)?

I currently have a working app but I don't know how to introduce animations.
Then I found your app through reddit and thought if the integration was possible.

Also if you want, you can use stockfish engine for flutter in your app.

**Comment by PScottZero** [comment]
I have an area of my code that calls my custom AI to get the AI's move that I could swap out for stockfish. I'll look into it and get back to you.

**Comment by PScottZero** [comment]
@ArjanAswal, I have written a branch where I replaced my custom AI with your stockfish package. Look at the files lib/logic/stockfish_ai.dart and lib/logic/chess_game.dart for the implementation. I may still have to do some work, but the basic implementation works. The branch can be found here: https://github.com/PScottZero/EnPassant/tree/stockfish

**Comment by ArjanAswal** [comment]
Thank you so much.

**Comment by ArjanAswal** [comment]
Hey @PScottZero What are the limitations that I should be aware of?

**Comment by PScottZero** [comment]
Not that I am aware of at this time
