### ISSUE TITLE
License for EnPassant?

### ISSUE THREAD

**Issue by vietanhdev** [PScottZero/EnPassant#5]
Hello,
Thank you for creating and sharing a beautiful chess app.
Can you specify the license for your project?
I want to use your source code as a starter for a commercial project without releasing my source code. Is it possible with your license?
Thank you very much!

**Comment by vietanhdev** [comment]
You may not be aware of this, but legally, without a license, no one can use your code.

<http://opensource.stackexchange.com/q/1720/775>

**Comment by PScottZero** [comment]
Added! Thanks for letting me know
